import numpy as np
import cirq
import sympy
import scipy.stats as stats
import matplotlib.pyplot as plt

def create_pqc_subsystem(n_qubits, n_layers=1):
    """
    Creates a PQC architecture similar to the one in phase5, but for a smaller number of qubits.
    n_qubits: Total number of qubits (including readout).
    """
    qubits = [cirq.GridQubit(i, 0) for i in range(n_qubits)]
    readout = qubits[-1]
    data_qubits = qubits[:-1]
    
    circuit = cirq.Circuit()
    symbols = []
    
    # Entanglement layer (linear chain for simplicity in subsystem)
    for i in range(len(data_qubits) - 1):
        circuit.append(cirq.CZ(data_qubits[i], data_qubits[i+1]))
    if len(data_qubits) > 0:
        circuit.append(cirq.CZ(data_qubits[-1], readout))
    
    # Parametric layers
    for l in range(n_layers):
        for i, q in enumerate(data_qubits):
            # XX gates
            symbol_xx = sympy.Symbol(f'xx-{l}-{i}')
            circuit.append(cirq.XX(q, readout)**symbol_xx)
            symbols.append(symbol_xx)
            # ZZ gates
            symbol_zz = sympy.Symbol(f'zz-{l}-{i}')
            circuit.append(cirq.ZZ(q, readout)**symbol_zz)
            symbols.append(symbol_zz)
            
    return circuit, qubits, symbols

def get_haar_distribution(n_qubits, n_bins=75):
    """Returns the Haar fidelity distribution for n_qubits."""
    d = 2**n_qubits
    fidelities = np.linspace(0, 1, n_bins)
    p_haar = (d - 1) * (1 - fidelities)**(d - 2)
    # Normalize
    p_haar /= np.sum(p_haar)
    return fidelities, p_haar

def sample_pqc_fidelities(circuit, qubits, symbols, n_samples=1000):
    """Samples fidelities between pairs of states generated by random parameters."""
    simulator = cirq.Simulator()
    fidelities = []
    
    for _ in range(n_samples):
        # Sample two sets of random parameters in [0, 2] (full rotation range for Cirq's exponent)
        params1 = {s: np.random.uniform(0, 2) for s in symbols}
        params2 = {s: np.random.uniform(0, 2) for s in symbols}
        
        # Get state vectors
        result1 = simulator.simulate(circuit, param_resolver=params1)
        state1 = result1.final_state_vector
        
        result2 = simulator.simulate(circuit, param_resolver=params2)
        state2 = result2.final_state_vector
        
        # Fidelity F = |<psi1|psi2>|^2
        fidelity = np.abs(np.vdot(state1, state2))**2
        fidelities.append(fidelity)
        
    return np.array(fidelities)

def calculate_expressibility(pqc_fidelities, n_qubits, n_bins=75):
    """Calculates the KL divergence between PQC and Haar distributions."""
    # Empirical distribution
    p_pqc, bin_edges = np.histogram(pqc_fidelities, bins=n_bins, range=(0, 1), density=True)
    p_pqc /= np.sum(p_pqc)
    
    # Haar distribution
    _, p_haar = get_haar_distribution(n_qubits, n_bins)
    
    # Add small epsilon to avoid log(0)
    epsilon = 1e-10
    p_pqc += epsilon
    p_haar += epsilon
    
    # KL Divergence: sum(P * log(P/Q))
    kl_div = np.sum(p_pqc * np.log(p_pqc / p_haar))
    return kl_div

def calculate_meyer_wallach(circuit, qubits, symbols, n_samples=100):
    """Calculates the Meyer-Wallach entanglement measure averaged over random parameters."""
    simulator = cirq.Simulator()
    n = len(qubits)
    q_measures = []
    
    for _ in range(n_samples):
        params = {s: np.random.uniform(0, 2) for s in symbols}
        result = simulator.simulate(circuit, param_resolver=params)
        state = result.final_state_vector
        
        sum_det = 0
        for i in range(n):
            # Reshape to (2, 2, 2, ...)
            reshaped_state = state.reshape([2]*n)
            # Move index i to the front
            permuted_state = np.moveaxis(reshaped_state, i, 0)
            # Flatten the rest
            reshaped_for_trace = permuted_state.reshape(2, -1)
            # rho_i = Tr_{not i} (|psi><psi|)
            rho_i = np.dot(reshaped_for_trace, reshaped_for_trace.T.conj())
            
            # det(rho_i)
            det_rho_i = np.linalg.det(rho_i)
            sum_det += det_rho_i
            
        q_psi = (4.0 / n) * np.real(sum_det)
        q_measures.append(q_psi)
        
    return np.mean(q_measures)

if __name__ == "__main__":
    n_qubits = 4
    results = []
    
    print(f"Running Expressibility & Entanglement Analysis for {n_qubits} qubits...")
    
    for layers in [1, 2, 3, 4, 5]:
        circuit, qubits, symbols = create_pqc_subsystem(n_qubits, layers)
        
        fidelities = sample_pqc_fidelities(circuit, qubits, symbols, n_samples=2000)
        expr = calculate_expressibility(fidelities, n_qubits)
        ent = calculate_meyer_wallach(circuit, qubits, symbols, n_samples=200)
        
        results.append({
            'layers': layers,
            'expressibility': expr,
            'entanglement': ent
        })
        
        print(f"Layers: {layers} | Expressibility: {expr:.4f} | Entanglement: {ent:.4f}")

    # Generate summary report
    print("\n--- Phase 7 Summary ---")
    for res in results:
        print(f"L={res['layers']}: Expr={res['expressibility']:.4f}, Ent={res['entanglement']:.4f}")
    
    # Save results to a file
    with open("phase7/results_rigor.txt", "w") as f:
        f.write("Phase 7: Expressibility & Entanglement Analysis\n")
        f.write("Architecture: PQC from Phase 5 (Subsystem of 4 qubits)\n")
        f.write("--------------------------------------------------\n")
        for res in results:
            f.write(f"Layers: {res['layers']}, Expressibility: {res['expressibility']:.4f}, Entanglement: {res['entanglement']:.4f}\n")
        
        f.write("\nAnalysis:\n")
        f.write("As the number of layers increases, the Expressibility value (KL divergence) should decrease,\n")
        f.write("indicating that the PQC is approaching the Haar distribution and can explore the Hilbert space more uniformly.\n")
        f.write("Similarly, the Meyer-Wallach entanglement measure should increase, showing that the circuit is capable\n")
        f.write("of generating more global entanglement.\n")
